server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:student.db
    username: 
    password: 
  sql:
    init:
      mode: always
      schema-locations: file:../Doc/Student.sql
      continue-on-error: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto